"""Typed UI metadata for native-engine inference parameters.

Only options that affect inference behavior/performance are surfaced. Output-format,
logging and debug-only CLI flags are intentionally excluded.
"""
from __future__ import annotations


WEIGHT_TYPES = ["native", "f32", "f16", "bf16", "q8_0"]


WHISPER = [
    dict(key="processors", type="int", default=1, min=1, max=128,
         en="Processors", ja="Processors",
         tip_en="Number of whisper.cpp processors used by the CLI.",
         tip_ja="whisper.cpp CLI が使用するprocessor数。"),
    dict(key="gpu_device", type="int", default=0, min=0, max=31,
         en="GPU device", ja="GPU device",
         tip_en="GPU device index passed to whisper.cpp.",
         tip_ja="whisper.cpp に渡すGPU device index。"),
    dict(key="flash_attn", type="bool", default=True,
         en="Flash attention", ja="Flash attention",
         tip_en="Enable whisper.cpp flash attention. Uncheck to pass --no-flash-attn.",
         tip_ja="whisper.cpp のflash attention。OFFでは --no-flash-attn を指定。"),
    dict(key="beam_size", type="int", default=5, min=1, max=64,
         en="Beam size", ja="Beam size",
         tip_en="Beam width used by whisper.cpp beam search.",
         tip_ja="whisper.cpp のビーム探索幅。"),
    dict(key="best_of", type="int", default=5, min=1, max=64,
         en="Best of", ja="Best of",
         tip_en="Number of candidates retained by sampling.",
         tip_ja="サンプリング時に保持する候補数。"),
    dict(key="temperature", type="float", default=0.0, min=0.0, max=1.0, step=0.05,
         en="Temperature", ja="Temperature",
         tip_en="Sampling temperature.",
         tip_ja="サンプリング温度。"),
    dict(key="temperature_inc", type="float", default=0.2, min=0.0, max=1.0, step=0.05,
         en="Temperature increment", ja="Temperature increment",
         tip_en="Temperature fallback increment.",
         tip_ja="フォールバック時の温度増分。"),
    dict(key="no_speech_thold", type="float", default=0.6, min=0.0, max=1.0, step=0.05,
         en="No-speech threshold", ja="無音判定しきい値",
         tip_en="Threshold used to classify a segment as no speech.",
         tip_ja="発話なしと判断するしきい値。"),
    dict(key="entropy_thold", type="float", default=2.4, min=0.0, max=20.0, step=0.1,
         en="Entropy threshold", ja="Entropy threshold",
         tip_en="Decoder failure entropy threshold.",
         tip_ja="デコーダ失敗判定のエントロピーしきい値。"),
    dict(key="logprob_thold", type="float", default=-1.0, min=-20.0, max=0.0, step=0.1,
         en="Logprob threshold", ja="Logprob threshold",
         tip_en="Decoder failure log-probability threshold.",
         tip_ja="デコーダ失敗判定の対数確率しきい値。"),
    dict(key="word_thold", type="float", default=0.01, min=0.0, max=1.0, step=0.01,
         en="Word timestamp threshold", ja="単語時刻しきい値",
         tip_en="Word timestamp probability threshold.",
         tip_ja="単語タイムスタンプの確率しきい値。"),
    dict(key="audio_ctx", type="int", default=0, min=0, max=16384,
         en="Audio context", ja="Audio context",
         tip_en="Audio context size; 0 uses the full model context.",
         tip_ja="音声コンテキスト長。0 はモデル既定の全長。"),
    dict(key="max_context", type="int", default=-1, min=-1, max=32768,
         en="Max text context", ja="最大テキスト文脈",
         tip_en="Maximum text-context tokens to retain; -1 uses the default.",
         tip_ja="保持するテキスト文脈token数。-1 は既定値。"),
    dict(key="max_len", type="int", default=0, min=0, max=4096,
         en="Max segment length", ja="最大セグメント長",
         tip_en="Maximum segment length in characters; 0 disables the limit.",
         tip_ja="セグメント最大文字数。0 は制限なし。"),
    dict(key="split_on_word", type="bool", default=False,
         en="Split on word", ja="単語境界で分割",
         tip_en="Prefer word boundaries when splitting output.",
         tip_ja="出力分割で単語境界を優先。"),
    dict(key="no_fallback", type="bool", default=False,
         en="Disable fallback", ja="Temperature fallbackを無効化",
         tip_en="Disable temperature fallback.",
         tip_ja="Temperature fallback を無効にします。"),
    dict(key="suppress_nst", type="bool", default=False,
         en="Suppress non-speech tokens", ja="非発話tokenを抑制",
         tip_en="Suppress non-speech tokens during decoding.",
         tip_ja="デコード中の非発話tokenを抑制。"),
    dict(key="suppress_regex", type="string", default="",
         en="Suppress regex", ja="抑制regex",
         tip_en="Regular expression matching tokens to suppress.",
         tip_ja="抑制するtokenに一致させる正規表現。"),
    dict(key="grammar", type="string", default="",
         en="Grammar", ja="Grammar",
         tip_en="GBNF grammar string passed to whisper.cpp.",
         tip_ja="whisper.cpp に渡すGBNF grammar文字列。"),
    dict(key="grammar_rule", type="string", default="",
         en="Grammar rule", ja="Grammar rule",
         tip_en="Starting grammar rule name.",
         tip_ja="grammarの開始rule名。"),
    dict(key="grammar_penalty", type="float", default=100.0, min=0.0, max=10000.0, step=1.0,
         en="Grammar penalty", ja="Grammar penalty",
         tip_en="Penalty applied to tokens rejected by the grammar.",
         tip_ja="grammarが拒否するtokenに適用するpenalty。"),
    dict(key="vad", type="bool", default=False,
         en="VAD", ja="VAD",
         tip_en="Enable whisper.cpp voice activity detection. A compatible VAD model is required.",
         tip_ja="whisper.cpp VADを有効化。互換VADモデルが必要。"),
    dict(key="vad_model", type="string", default="",
         en="VAD model", ja="VAD model",
         tip_en="Path to a whisper.cpp-compatible VAD model.",
         tip_ja="whisper.cpp互換VADモデルのパス。"),
    dict(key="vad_threshold", type="float", default=0.5, min=0.0, max=1.0, step=0.01,
         en="VAD threshold", ja="VAD threshold",
         tip_en="Voice activity probability threshold.",
         tip_ja="音声activityの確率しきい値。"),
    dict(key="vad_min_speech_duration_ms", type="int", default=250, min=0, max=600000, suffix=" ms",
         en="VAD min speech", ja="VAD最小発話",
         tip_en="Minimum speech duration accepted by VAD.",
         tip_ja="VADが発話として受け入れる最小時間。"),
    dict(key="vad_min_silence_duration_ms", type="int", default=100, min=0, max=600000, suffix=" ms",
         en="VAD min silence", ja="VAD最小無音",
         tip_en="Minimum silence duration used by VAD segmentation.",
         tip_ja="VAD分割で使用する最小無音時間。"),
    dict(key="vad_max_speech_duration_s", type="float", default=0.0, min=0.0, max=86400.0, step=1.0, suffix=" s",
         en="VAD max speech", ja="VAD最大発話",
         tip_en="Maximum VAD speech segment duration; 0 leaves whisper.cpp at its native unlimited default.",
         tip_ja="VAD発話segmentの最大秒数。0ではwhisper.cppの無制限既定値を使用。"),
    dict(key="vad_speech_pad_ms", type="int", default=30, min=0, max=60000, suffix=" ms",
         en="VAD speech pad", ja="VAD speech pad",
         tip_en="Padding added around detected speech.",
         tip_ja="検出発話の前後へ追加するpadding。"),
    dict(key="vad_samples_overlap", type="float", default=0.1, min=0.0, max=1.0, step=0.01,
         en="VAD overlap", ja="VAD overlap",
         tip_en="Sample overlap used between VAD chunks.",
         tip_ja="VAD chunk間のsample overlap。"),
    dict(key="translate", type="bool", default=False,
         en="Translate to English", ja="英語へ翻訳",
         tip_en="Ask whisper.cpp to translate speech into English.",
         tip_ja="文字起こし結果を英語へ翻訳。"),
    dict(key="initial_prompt", type="string", default="",
         en="Initial prompt", ja="初期プロンプト",
         tip_en="Initial prompt passed to whisper.cpp.",
         tip_ja="whisper.cpp に渡す初期プロンプト。"),
    dict(key="carry_initial_prompt", type="bool", default=False,
         en="Carry initial prompt", ja="初期プロンプトを継続",
         tip_en="Prepend the initial prompt on subsequent decoding windows.",
         tip_ja="後続ウィンドウにも初期プロンプトを付与。"),
]


AUDIO = {
    "mel_band_roformer": [
        dict(key="session.num_overlap", type="int", default=2, min=1, max=16,
             en="Overlap windows", ja="Overlap windows",
             tip_en="Number of overlapping separation windows. Higher values trade speed/memory for boundary quality.",
             tip_ja="分離窓の重なり数。大きいほど境界品質と引き換えに速度・メモリを消費。"),
        dict(key="session.weight_type", type="enum", default="native", values=WEIGHT_TYPES,
             en="Runtime weight type", ja="実行時weight type",
             tip_en="Runtime tensor storage requested from audio.cpp.",
             tip_ja="audio.cpp に要求する実行時tensor storage。"),
    ],
    "nemotron_3_diar": [
        dict(key="speaker_threshold", type="float", default=0.5, min=0.0, max=1.0, step=0.01,
             en="Speaker threshold", ja="話者しきい値",
             tip_en="Speaker activity threshold used for turn decoding.",
             tip_ja="話者activityをturnへ復号するしきい値。"),
        dict(key="speaker_min_frames", type="int", default=0, min=0, max=10000,
             en="Minimum turn frames", ja="最小turn frames",
             tip_en="Minimum decoded turn duration in 10 ms frames.",
             tip_ja="turnの最小長。10ms frame単位。"),
        dict(key="speaker_pad_frames", type="int", default=0, min=0, max=10000,
             en="Turn padding frames", ja="turn padding frames",
             tip_en="Padding added to decoded turns in 10 ms frames.",
             tip_ja="turnへ追加するpadding。10ms frame単位。"),
        dict(key="session.latency_profile", type="enum", default="very_high",
             values=["very_high", "low", "very_low", "ultra_low", "custom"],
             en="Latency profile", ja="Latency profile",
             tip_en="Official Nemotron diarization latency profile.",
             tip_ja="Nemotron diarization公式latency profile。"),
        dict(key="session.spkcache_len", type="int", default=188, min=16, max=100000,
             en="Speaker cache length", ja="Speaker cache length",
             tip_en="Speaker-cache length in 80 ms encoder frames for the custom profile.",
             tip_ja="custom profile用speaker cache長。80ms frame単位。"),
        dict(key="session.fifo_len", type="int", default=40, min=0, max=100000,
             en="FIFO length", ja="FIFO length",
             tip_en="FIFO length in 80 ms encoder frames for the custom profile.",
             tip_ja="custom profile用FIFO長。80ms frame単位。"),
        dict(key="session.chunk_len", type="int", default=6, min=1, max=100000,
             en="Chunk length", ja="Chunk length",
             tip_en="Chunk length in 80 ms encoder frames for the custom profile.",
             tip_ja="custom profile用chunk長。80ms frame単位。"),
        dict(key="session.chunk_right_context", type="int", default=7, min=0, max=100000,
             en="Right context", ja="Right context",
             tip_en="Future context in 80 ms frames for the custom profile.",
             tip_ja="custom profile用future context。80ms frame単位。"),
        dict(key="session.spkcache_update_period", type="int", default=144, min=1, max=100000,
             en="Cache update period", ja="Cache update period",
             tip_en="FIFO-to-cache update period in 80 ms frames.",
             tip_ja="FIFOからcacheへの更新周期。80ms frame単位。"),
        dict(key="session.graph_arena_mb", type="int", default=1024, min=1, max=32768,
             en="Graph arena", ja="Graph arena", suffix=" MB",
             tip_en="Inference graph arena size.",
             tip_ja="推論graph arenaサイズ。"),
        dict(key="session.weight_context_mb", type="int", default=1024, min=1, max=32768,
             en="Weight context", ja="Weight context", suffix=" MB",
             tip_en="Weight context size.",
             tip_ja="weight contextサイズ。"),
        dict(key="session.weight_type", type="enum", default="native", values=WEIGHT_TYPES,
             en="Runtime weight type", ja="実行時weight type",
             tip_en="Runtime model weight storage type.",
             tip_ja="実行時モデルweight storage type。"),
    ],
    "qwen3_forced_aligner": [
        dict(key="clamp_timestamps_to_audio", type="bool", default=False,
             en="Clamp timestamps to audio", ja="時刻を音声範囲内に制限",
             tip_en="Clamp repaired word spans inside each local audio chunk.",
             tip_ja="補正後の単語区間をローカル音声範囲内へ制限。"),
    ],
    "mms_forced_aligner": [
        dict(key="text_normalization", type="enum", default="latin", values=["latin", "pre_romanized"],
             en="Text normalization", ja="テキスト正規化",
             tip_en="Transcript normalization mode.",
             tip_ja="transcriptの正規化モード。"),
        dict(key="star_frequency", type="enum", default="segment", values=["segment", "edges"],
             en="Star frequency", ja="Star frequency",
             tip_en="Placement policy for the virtual CTC star target.",
             tip_ja="仮想CTC star targetの配置方法。"),
        dict(key="merge_threshold_sec", type="float", default=0.0, min=0.0, max=30.0, step=0.01,
             en="Merge threshold", ja="結合しきい値", suffix=" s",
             tip_en="Merge adjacent words separated by less than this gap.",
             tip_ja="この秒数未満のgapにある隣接単語を結合。"),
        dict(key="session.emission_window_sec", type="float", default=30.0, min=0.02, max=3600.0, step=1.0,
             en="Emission window", ja="Emission window", suffix=" s",
             tip_en="Center emission window length for long waveforms.",
             tip_ja="長音声のcenter emission window長。"),
        dict(key="session.emission_context_sec", type="float", default=2.0, min=0.0, max=3600.0, step=0.1,
             en="Emission context", ja="Emission context", suffix=" s",
             tip_en="Left/right context appended to emission windows.",
             tip_ja="emission windowへ追加する左右context。"),
        dict(key="session.max_alignment_cells", type="int", default=50000000, min=1, max=1000000000,
             en="Max alignment cells", ja="最大alignment cells",
             tip_en="Hard cap on CTC dynamic-programming cells.",
             tip_ja="CTC動的計画法cell数の上限。"),
        dict(key="session.max_target_tokens", type="int", default=8192, min=1, max=1000000,
             en="Max target tokens", ja="最大target tokens",
             tip_en="Hard cap on flattened CTC target tokens.",
             tip_ja="CTC target token数の上限。"),
        dict(key="session.weight_type", type="enum", default="native", values=WEIGHT_TYPES,
             en="Runtime weight type", ja="実行時weight type",
             tip_en="Runtime weight storage type.",
             tip_ja="実行時weight storage type。"),
    ],
}


def specs_for(model) -> list[dict]:
    if model.runtime == "whisper_cpp":
        specs = WHISPER
    else:
        specs = AUDIO.get(model.family, [])
    result = []
    for original in specs:
        # The anime-whisper distributor explicitly warns against an initial prompt.
        if model.id == "anime-whisper" and original["key"] in {"initial_prompt", "carry_initial_prompt"}:
            continue
        spec = dict(original)
        key = spec["key"]
        if key.startswith("session."):
            plain = key[len("session."):]
            default = model.defaults.get("session", {}).get(plain, spec.get("default"))
        else:
            default = model.defaults.get("request", {}).get(key, spec.get("default"))
        spec["default"] = default
        result.append(spec)
    return result
